name: CD

on:
  push:
    branches: [ main ]

env:
  S3_BUCKET_NAME: petkpetk-bucket
  PROJECT_NAME: petkpetk

jobs:
  admin-build:
    name: admin build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.18'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x admin/gradlew
        shell: bash

      - name: Build with Gradle
        run: cd admin && ./gradlew build -x test
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name petkpetk \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name petkpetk-prod \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=petkpetk-bucket,bundleType=zip,key=petkpetk/$GITHUB_SHA.zip \
          --region ap-northeast-2 \
