name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  admin-build:
    name: admin Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.18'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x admin/gradlew
        shell: bash

      - name: Build with Gradle
        run: cd admin && ./gradlew build -x test
        shell: bash


#      - name: Replace secrets in application.yml
#        run: |
#          sed -i "s/\${AWS_DB_USERNAME}/${AWS_DB_USERNAME}/g" admin/src/main/resources/application.yml
#          sed -i "s/\${AWS_DB_PASSWORD}/${AWS_DB_PASSWORD}/g" admin/src/main/resources/application.yml
#          sed -i "s/\${GOOGLE_SMTP_USERNAME}/${GOOGLE_SMTP_USERNAME}/g" admin/src/main/resources/application.yml
#          sed -i "s/\${GOOGLE_SMTP_PASSWORD}/${GOOGLE_SMTP_PASSWORD}/g" admin/src/main/resources/application.yml
#        shell: bash
