name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  admin-build:
    name: admin Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.18'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x admin/gradlew
        shell: bash

      - name: Build with Gradle
        run: cd admin && ./gradlew build -x test
        shell: bash
